name: non-inclusive

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
